### ISSUE TITLE
Throwing errors .env file not in directory - How to configure

### ISSUE THREAD

**Issue by ramfury1** [ozgen/binance-telegram-bot#30]
Please find the attached image, I tried my level best but still I cant figure out as im new to java,

as said in description there is .env file where i need to add my configurations

and my signal group will have different format with minimal words, so how to setup the bot to make it recognise the signal

and execute the trade, Please do help to fix.
<img width="1661" alt="Screenshot 2024-03-26 at 9 22 20 PM" src="https://github.com/ozgen/binance-telegram-bot/assets/124815046/c482fe53-b3fe-4d1a-9ea6-dd0197f4b532">

**Comment by ozgen** [comment]
can you please send the stack trace, because I did not understand what happened in your local.
here is the sample of env.file:

```
AZURE_DB_PASSWORD=<db-password>
AZURE_DB_URL=<azure-db-url>
AZURE_DB_USERNAME=<db-user-name>
AZURE_KEYVAULT_CLIENT_ID=<azure-keyvault-client-id>
AZURE_KEYVAULT_CLIENT_KEY=<azure-keyvault-client-key>
AZURE_KEYVAULT_TENANT_ID=<azure-keyvault-tenant-id>
AZURE_KEYVAULT_URL=<keyvault-url>
TELEGRAM_ERROR_TOKEN=<telegram-error-token>
TELEGRAM_TOKEN=<telegram-channel-token>
TELEGRAM_USERNAME=<telegram-bot-username>
```

**Comment by ramfury1** [comment]
ramfury1@Rams-MacBook-Pro binance-telegram-bot % mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< com.ozgen:telegram-binance-bot >-------------------
[INFO] Building telegram-binance-bot 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.7:prepare-agent (prepare-agent) @ telegram-binance-bot ---
[INFO] argLine set to -javaagent:/Users/ramfury1/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/Users/ramfury1/Downloads/binance-telegram-bot/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ telegram-binance-bot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ telegram-binance-bot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 82 source files to /Users/ramfury1/Downloads/binance-telegram-bot/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.038 s
[INFO] Finished at: 2024-03-27T11:33:42+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project telegram-binance-bot: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ramfury1@Rams-MacBook-Pro binance-telegram-bot % 


Is this all you need?

**Comment by ozgen** [comment]
please comment out the `jacoco` plugin and try again 
  ```
<plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.7</version> <!-- Use the latest version -->
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by ramfury1** [comment]
Even after removing the above code in pom.xml still the issue not resolved

And also mention on how to make a env file

ramfury1@Rams-MacBook-Pro binance-telegram-bot % mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< com.ozgen:telegram-binance-bot >-------------------
[INFO] Building telegram-binance-bot 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ telegram-binance-bot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ telegram-binance-bot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 82 source files to /Users/ramfury1/Downloads/binance-telegram-bot/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.070 s
[INFO] Finished at: 2024-03-27T13:24:51+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project telegram-binance-bot: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ramfury1@Rams-MacBook-Pro binance-telegram-bot %

**Comment by ozgen** [comment]
Sorry my mistake there are mismatch between JDK version used at runtime and compile time so please use Java 11 for both of them and try again

**Comment by ramfury1** [comment]
Now the build is success

Now how i can configure with .env file, should i create a new file naming '.env' or ?

and what are all the required details in env file,

how can i configure the message from telegram which will be processed (The trade signals which will i receive will be in different format - so how i will make this code to understand the format and execute trade)

please guide through some more as java is completely new to me

**Comment by ozgen** [comment]
I will write a guideline and I may update the Readme.md

**Comment by ramfury1** [comment]
When can we expect the new readme

**Comment by ozgen** [comment]
The readme has been updated. FYI...
